### ISSUE TITLE
Feature request: message for new method on running flip()

### ISSUE THREAD

**Issue by noamross** [MilesMcBain/flippingtables#2]
I think it would be useful for `printer_fns` in `register_flips()` to be an optionally _named_ list of functions.  Then, on running `flip()`, if the flipped-to function has a name, a message is printed such as `flipped to print method: <name>`.  You might set names to things like "paint", or "tibble".  If no printing is desired, just don't add names to the list.

**Comment by MilesMcBain** [comment]
Yes, this will be good!
